version: '3'

services:
  reverse-proxy:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/acme.json
      - ./traefik-data/configurations:/configurations
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.traefik-secure.entrypoints=web"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.local.com`)"
      - "traefik.http.routers.traefik-secure.service=api@internal"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.rule=Host(`portainer.local.com`)"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  rabbitmq:
    image: 'rabbitmq:3.8.22-management-alpine'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.rabbitmq.rule=Host(`${COMPOSE_PROJECT_NAME}-web.rabbitmq.local`)"
      - "traefik.http.routers.rabbitmq.entrypoints=web"
      - "traefik.http.routers.rabbitmq.service=rabbitmq"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
      - "traefik.tcp.routers.ingress.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.ingress.entrypoints=rabbitmq"
      - "traefik.tcp.services.ingress.loadbalancer.server.port=5672"

    volumes:
      - 'rabbitmqdata:/var/lib/rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_USER=${PROJECT_RABBITMQ_USER}'
      - 'RABBITMQ_DEFAULT_PASS=${PROJECT_RABBITMQ_PASS}'
      - 'RABBITMQ_DEFAULT_VHOST=${PROJECT_RABBITMQ_VHOST}'
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=1024MB
    networks:
      - web
      - magento

  redis:
    hostname: redis.magento2.docker
    image: 'redis:5.0'
    volumes:
      - 'redis-sync:/redis:delegated'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.tcp.routers.redis-ingress.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.redis-ingress.entrypoints=redis"
      - "traefik.tcp.services.redis-ingress.loadbalancer.server.port=6379"

    healthcheck:
      test: redis-cli ping || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - web
      - magento


  elasticsearch:
    restart: always
    hostname: elasticsearch.magento2.docker
    image: 'magento/magento-cloud-docker-elasticsearch:6.5-1.3.0'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      - "traefik.tcp.routers.elasticsearch.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.elasticsearch.entrypoints=elasticsearch"
      - "traefik.tcp.services.elasticsearch.loadbalancer.server.port=9200"
    networks:
      - web
      - magento

  mailhog:
    hostname: mailhog.magento2.docker
    image: 'mailhog/mailhog:latest'
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.tcp.routers.mail-ingress.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mail-ingress.entrypoints=mailhog1"
      - "traefik.tcp.services.mail-ingress.loadbalancer.server.port=1025"
      - "traefik.tcp.routers.mails-ingress.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mails-ingress.entrypoints=mailhog2"
      - "traefik.tcp.services.mails-ingress.loadbalancer.server.port=8025"
    networks:
      - web

  phpmyadmin:
    image: phpmyadmin
    hostname: db-phpmyadmin.magento2.docker
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.local`)"
      - "traefik.http.routers.phpmyadmin.service=phpmyadmin"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - web
      - magento

volumes:
  rabbitmqdata: {}
  redis-sync: {}

networks:
  web:
    external: true
  magento:
    driver: bridge
    external: false